#!/usr/bin/env bash
set -e

# ========== CHECK CLEAN WORKING DIRECTORY ==========
if [[ -n "$(git status --porcelain)" ]]; then
  echo "❌ Error: Your working directory is not clean."
  echo "Please commit or stash your changes before running this script."
  exit 1
fi

# ========== CHECK GIT CONFIG ==========
GIT_NAME=$(git config user.name || true)
GIT_EMAIL=$(git config user.email || true)

if [[ -z "$GIT_NAME" || -z "$GIT_EMAIL" ]]; then
  echo "❌ Error: Git user.name or user.email is not configured."
  echo "Please configure them using the following commands:"
  echo ""
  echo "  git config --global user.name \"Your Name\""
  echo "  git config --global user.email \"you@example.com\""
  echo ""
  exit 1
fi

# ========== CHECK GH INSTALLED ==========
if ! command -v gh &>/dev/null; then
  echo "❌ Error: GitHub CLI (gh) is not installed."
  echo "Please install it first:"
  echo ""
  echo "  macOS: brew install gh"
  echo "  Ubuntu: sudo apt install gh"
  echo "  Windows: winget install --id GitHub.cli"
  echo ""
  echo "Then authenticate with:"
  echo "  gh auth login"
  exit 1
fi

# ========== CHECKOUT MAIN ==========
git fetch origin
git checkout main
git pull origin main

# ========== GET NEXT VERSION ==========
VERSION=$(node ./scripts/get-next-prerelease.js origin/rc origin/main | grep BETA_VERSION | cut -d'=' -f2)

if [[ -z "$VERSION" ]]; then
  echo "❌ Error: Failed to retrieve beta version."
  exit 1
fi

echo "📦 Next Beta Version: $VERSION"

# ========== CREATE & PUSH BRANCH ==========
BRANCH_NAME="cut-off/${VERSION}"
git checkout -b "$BRANCH_NAME"
git push -u origin "$BRANCH_NAME"

# ========== CREATE PR ==========
gh pr create \
  --base rc \
  --head "$BRANCH_NAME" \
  --title "[RELEASE][STAGING] ${VERSION}" \
  --body "This Pull Request is generated by \`./cut-off.sh\` script by @${GIT_NAME}"

git checkout main

echo "✅ Pull request created successfully!"
